<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Skyscreen.Server-cf8f4288-34a4-4a8e-9390-924155974ba4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="SkiaSharp" Version="4.153.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Skyscreen.Core\Skyscreen.Core.csproj" />
  </ItemGroup>
</Project>
